name: Expo Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli eas-cli

      - name: Build APK
        run: eas build -p android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}